[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sat-clas"
version = "0.3.0"
description = "Local satellite segmentation, geographic search and map explorer"
readme = "README.md"
requires-python = ">=3.11"
dynamic = ["dependencies"]

[project.optional-dependencies]
dev = ["playwright"]

[project.scripts]
sat-clas = "src.cli:main"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.package-data]
"src.interface" = ["static/*"]
"src" = ["default_config.yaml"]

[tool.setuptools.packages.find]
where = ["."]
include = ["src", "src.*"]
